version: "1.0"
services:
  dashboard:
    build: .
    ports:
      - 8501:8501
    volumes:
      - ./conf:/app/conf
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5432:5432