database:
  dbms: postgresql
  # Set to host: localhost for running from code base
  host: host.docker.internal
  port: 5432
  user: postgres
  password: postgres

mapping:
  columns:
    user_id: user_id
    timestamp: timestamp
    value: value
  tables:
    user_table:
      name: geomts_users
      columns:
        user_id: String(50)
        device: String(50)
        location: String(50)
    time_series:
      - heart_rates
      - calories
      - distances
      - steps
      - sleep
      - weight
    geo:
      - locations
